const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { absolutize, UPLOAD_ROOT } = require('../cloudinary/storage.service');

const BRAND = {
  name: 'Legal Metrology Compliance Intelligence Platform',
  authority: 'Department of Consumer Affairs — Legal Metrology',
  accent: '#0f3d6e',
  light: '#eef2f7',
};

async function loadImageBuffer(url) {
  try {
    if (!url) return null;
    if (url.startsWith('data:image/')) {
      const base64Data = url.replace(/^data:image\/\w+;base64,/, '');
      return Buffer.from(base64Data, 'base64');
    }
    // Prefer reading local files directly from disk without network overhead
    if (url.startsWith('/uploads') || url.includes('uploads/')) {
      const rel = url.replace(/^.*uploads\//, '');
      const localPath = path.join(UPLOAD_ROOT, rel);
      if (fs.existsSync(localPath)) return fs.readFileSync(localPath);
    }
    const abs = absolutize(url);
    if (/^https?:\/\//i.test(abs)) {
      const res = await fetch(abs);
      if (!res.ok) return null;
      return Buffer.from(await res.arrayBuffer());
    }
    const localPath = path.join(UPLOAD_ROOT, url.replace(/^\/?uploads\//, ''));
    if (fs.existsSync(localPath)) return fs.readFileSync(localPath);
    return null;
  } catch {
    return null;
  }
}

function fmtDate(d) {
  if (!d) return '-';
  return new Date(d).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
}

/**
 * Generate a professional government-style compliance report.
 * Returns { buffer } (caller persists it).
 */
async function generateInspectionPdf({ inspection, product, generatedBy }) {
  // Checksum is computed over the verified content snapshot (stored in DB alongside
  // the file) so any tampering with either artifact is detectable.
  const { sha256Hex } = require('../../utils/ids');
  const prodName = product?.productName || inspection.declarations?.PRODUCT_NAME?.value || 'Unknown Product';
  const contentChecksum = sha256Hex(
    JSON.stringify({
      id: inspection.inspectionId,
      status: inspection.finalStatus,
      scores: inspection.scores || {},
      violations: (inspection.violations || []).map((v) => [v.ruleCode, v.extractedValue, v.severity]),
      product: prodName,
      generatedBy: generatedBy?._id?.toString?.() || '',
    })
  );

  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 44, bufferPages: true });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve({ buffer: Buffer.concat(chunks), checksum: contentChecksum }));
      doc.on('error', reject);

    const W = doc.page.width - 88;

    // ---------- Header ----------
    doc.rect(0, 0, doc.page.width, 96).fill(BRAND.accent);
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(16)
      .text(BRAND.name, 44, 24, { width: W });
    doc.font('Helvetica').fontSize(9)
      .text(`${BRAND.authority} | Inspection Report`, 44);
    doc.fontSize(8).fillColor('#cfe0f5')
      .text('Automated compliance-assistance output — subject to verification by the competent authority.', 44);

    let y = 116;

    // ---------- Meta block ----------
    const meta = [
      ['Inspection ID', inspection.inspectionId],
      ['Report Generated', fmtDate(new Date())],
      ['Generated By', `${generatedBy?.name || ''} (${generatedBy?.role || ''})`],
      ['Inspector', inspection.inspectorId?.name || '-'],
      ['Inspection Date', fmtDate(inspection.createdAt)],
      ['Location', [inspection.location?.city, inspection.location?.district, inspection.location?.state].filter(Boolean).join(', ') || '-'],
    ];
    doc.rect(44, y, W, 92).fillAndStroke('#f7f9fc', '#d5dde8');
    meta.forEach(([k, v], i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = 56 + col * (W / 2);
      const yy = y + 12 + row * 28;
      doc.fillColor('#66708a').font('Helvetica').fontSize(8).text(k.toUpperCase(), x, yy);
      doc.fillColor('#111827').font('Helvetica-Bold').fontSize(10).text(String(v), x, yy + 10, {
        width: W / 2 - 24,
        ellipsis: true,
      });
    });
    y += 108;

    // ---------- Status banner ----------
    const statusColors = {
      COMPLIANT: '#0f9d58', PASS_AFTER_REVIEW: '#0f9d58', VIOLATION_CONFIRMED: '#d23f31',
      NON_COMPLIANT: '#d23f31', REQUIRES_REVIEW: '#e8a300',
    };
    const statusLabel = String(inspection.finalStatus || '').replace(/_/g, ' ');
    doc.roundedRect(44, y, W, 40, 4).fill(statusColors[inspection.finalStatus] || '#555');
    doc.fillColor('#fff').font('Helvetica-Bold').fontSize(13)
      .text(`STATUS: ${statusLabel}`, 60, y + 12);
    doc.fontSize(11)
      .text(
        `Compliance Score: ${Math.round(inspection.scores?.overall ?? 0)}%`,
        380, y + 13, { align: 'right', width: W - 352 }
      );
    y += 56;

    // ---------- Product info ----------
    sectionTitle(doc, 'PRODUCT INFORMATION', y); y += 20;
    const pRows = [
      ['Product Name', product?.productName || prodName],
      ['Brand', product?.brandName || cleanDeclsValue(inspection, 'BRAND_NAME') || '-'],
      ['Category', String(product?.category || '').replace(/_/g, ' ') || '-'],
      ['Barcode', product?.barcode || '-'],
      ['Manufacturer', product?.manufacturer || cleanDeclsValue(inspection, 'MANUFACTURER_NAME') || '-'],
      ['Packer', product?.packer || cleanDeclsValue(inspection, 'PACKER_NAME') || '-'],
      ['Importer', product?.importer || cleanDeclsValue(inspection, 'IMPORTER_NAME') || '-'],
    ];
    twoColTable(doc, pRows, y); y += Math.ceil(pRows.length / 2) * 30 + 10;

    // ---------- Images ----------
    const imgs = (inspection.images || []).filter((i) => i.url).slice(0, 4);
    if (imgs.length) {
      sectionTitle(doc, 'INSPECTION IMAGES', y); y += 18;
      const cellW = (W - 12 * (imgs.length - 1)) / imgs.length;
      const cellH = 110;
      for (let i = 0; i < imgs.length; i++) {
        const buf = await loadImageBuffer(imgs[i].url);
        const x = 44 + i * (cellW + 12);
        if (buf) {
          try {
            doc.image(buf, x, y, { fit: [cellW, cellH - 14], align: 'center' });
          } catch {}
        } else {
          doc.rect(x, y, cellW, cellH - 14).fillAndStroke('#f2f4f8', '#d5dde8');
          doc.fillColor('#98a2b3').font('Helvetica').fontSize(7)
            .text('[image unavailable]', x + 4, y + (cellH - 14) / 2, { width: cellW - 8, align: 'center' });
        }
        doc.fillColor('#66708a').font('Helvetica').fontSize(7)
          .text(imgs[i].label || '', x, y + cellH - 10, { width: cellW, align: 'center' });
      }
      y += cellH + 12;
    }

    doc.addPage();
    y = 44;

    // ---------- Extracted declarations ----------
    sectionTitle(doc, 'EXTRACTED DECLARATIONS (OCR + HUMAN REVIEW)', y); y += 18;
    const decls = Object.entries(inspection.declarations || {}).filter(([, v]) => v && v.value);
    declTableHeader(doc, y); y += 16;
    if (decls.length === 0) {
      doc.font('Helvetica').fontSize(9).fillColor('#66708a')
        .text('No declarations recorded.', 48, y); y += 22;
    }
    decls.forEach(([key, entry]) => {
      const verified = entry.humanVerified ? '[HUMAN VERIFIED]' : `[${Math.round((entry.confidence ?? 0) * 100)}%]`;
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#374151')
        .text(key.replace(/_/g, ' '), 48, y, { width: 150 });
      doc.font('Helvetica').fontSize(8).fillColor('#111827')
        .text(truncate(entry.value, 70), 200, y, { width: 210 });
      doc.font('Helvetica').fontSize(7).fillColor(entry.humanVerified ? '#0f9d58' : '#66708a')
        .text(verified, 415, y + 1, { width: 60, align: 'center' });
      doc.font('Helvetica').fontSize(7).fillColor('#66708a')
        .text(entry.sourceImageIndex !== undefined ? `IMG ${entry.sourceImageIndex + 1}` : '-', 480, y + 1);
      y += 17;
      if (y > doc.page.height - 120) { doc.addPage(); y = 44; }
    });
    y += 10;

    // ---------- Violations ----------
    sectionTitle(doc, `VIOLATIONS (${(inspection.violations || []).length})`, y); y += 18;
    if (!inspection.violations?.length) {
      doc.font('Helvetica').fontSize(9).fillColor('#0f9d58').text('No violations detected.', 48, y);
      y += 26;
    }
    (inspection.violations || []).forEach((v, idx) => {
      if (y > doc.page.height - 170) { doc.addPage(); y = 44; }
      const sevColors = { CRITICAL: '#b71c1c', HIGH: '#d23f31', MEDIUM: '#e8a300', LOW: '#8b90a0' };
      doc.roundedRect(44, y, W, 108, 4).lineWidth(0.8).stroke('#d5dde8');
      doc.roundedRect(44, y, 64, 16, 2).fill(sevColors[v.severity] || '#888');
      doc.fillColor('#fff').font('Helvetica-Bold').fontSize(7).text(v.severity, 46, y + 4.5, { width: 62, align: 'center' });
      doc.fillColor('#111827').font('Helvetica-Bold').fontSize(10)
        .text(`${idx + 1}. ${v.ruleTitle}`, 118, y + 3, { width: W - 130 });
      doc.fillColor('#66708a').font('Helvetica').fontSize(7.5)
        .text(`${v.ruleCode} | ${String(v.category || '').replace(/_/g, ' ')} | Rule Ref: ${v.sourceReference || '-'}`, 118, y + 17, { width: W - 130 });
      doc.fillColor('#374151').fontSize(8.5)
        .text(`Detected: ${v.extractedValue ?? 'NOT FOUND'}   Expected: ${truncate(v.expectedRequirement || '', 110)}`, 50, y + 32, { width: W - 14 });
      doc.fillColor('#374151')
        .text(`Why flagged: ${truncate(v.reason || '', 160)}`, 50, y + 45, { width: W - 14 });
      const ex = v.explainability || {};
      doc.fillColor('#475569').fontSize(7.5)
        .text(`Verify manually: ${truncate(ex.inspectorShouldVerify || '-', 180)}`, 50, y + 58, { width: W - 14 });
      doc.fillColor('#98a2b3').fontSize(7)
        .text(`Evidence confidence: ${Math.round((v.confidence ?? 0) * 100)}%`, 50, y + 72);
      if (ex.ruleApplied) doc.text(ex.ruleApplied, 50, y + 82, { width: W - 14 });
      y += 118;
    });

    // ---------- Checks summary ----------
    if (y > doc.page.height - 220) { doc.addPage(); y = 44; }
    sectionTitle(doc, 'RULE-BY-RULE CHECK SUMMARY', y); y += 18;
    checkTableHeader(doc, y); y += 16;
    (inspection.complianceChecks || []).forEach((c) => {
      if (y > doc.page.height - 80) { doc.addPage(); y = 44; checkTableHeader(doc, y); y += 16; }
      const statusColor = c.status === 'PASS' ? '#0f9d58' : c.status === 'FAIL' ? '#d23f31' : c.status === 'WARNING' ? '#e8a300' : '#8b90a0';
      doc.font('Helvetica').fontSize(7.5).fillColor('#374151')
        .text(c.ruleCode, 48, y, { width: 100 });
      doc.text(truncate(c.ruleTitle || '', 42), 148, y, { width: 190 });
      doc.fillColor(statusColor).font('Helvetica-Bold')
        .text(c.status + (c.manualVerificationRequired ? '*' : ''), 340, y, { width: 78 });
      doc.fillColor('#374151').font('Helvetica')
        .text(`${Math.round((c.confidence ?? 0) * 100)}%`, 420, y, { width: 40, align: 'right' });
      doc.text(String(Math.round(inspection.scores?.overall ?? 0)) , 0, 0, { lineBreak: false }); // noop keep font
      doc.fillColor('#66708a').fontSize(7)
        .text(truncate(c.sourceReference || '', 52), 462, y + 1, { width: 85 });
      y += 16;
    });
    doc.font('Helvetica-Oblique').fontSize(7).fillColor('#66708a')
      .text('* Manual verification required for reliable determination.', 48, y + 4);
    y += 24;

    // ---------- Inspector notes ----------
    sectionTitle(doc, 'INSPECTOR REMARKS', y); y += 18;
    doc.roundedRect(44, y, W, 54, 4).fillAndStroke('#fbfbfd', '#d5dde8');
    doc.fillColor('#111827').font('Helvetica').fontSize(9)
      .text(inspection.inspectorNotes || '—', 52, y + 8, { width: W - 16 });
    y += 68;

    // Review info
    if (inspection.reviewed) {
      doc.font('Helvetica').fontSize(8.5).fillColor('#374151')
        .text(
          `Reviewed by: ${inspection.reviewedBy?.name || '-'} on ${fmtDate(inspection.reviewedAt)} — Decision: ${String(inspection.finalStatus).replace(/_/g, ' ')}`,
          48, y
        );
      if (inspection.reviewRemarks) doc.fillColor('#475569').text(`Remarks: ${inspection.reviewRemarks}`, 48, y + 14);
      y += inspection.reviewRemarks ? 40 : 24;
    }

    // ---------- Digital verification ----------
    if (y > doc.page.height - 140) { doc.addPage(); y = 44; }
    sectionTitle(doc, 'DIGITAL VERIFICATION', y); y += 18;
    doc.font('Helvetica').fontSize(8).fillColor('#374151')
      .text('The SHA-256 checksum below covers the inspection content snapshot of this report', 44, y);
    doc.text('and is stored in the platform database for tamper detection.', 44, y + 10);
    doc.font('Courier-Bold').fontSize(7.5).fillColor('#111827')
      .text(contentChecksum, 44, y + 24, { width: W });
    y += 42;

    // ---------- Disclaimer ----------
    doc.roundedRect(44, y, W, 44, 4).fill('#fdf6ec');
    doc.fillColor('#8a6100').font('Helvetica-Bold').fontSize(7.5)
      .text('DISCLAIMER:', 52, y + 7);
    doc.font('Helvetica').fontSize(7.5)
      .text(
        'This report is an automated compliance-assistance output and is subject to verification by the competent authority. It does not constitute a legal determination under the Legal Metrology Act, 2009.',
        52, y + 18, { width: W - 16 }
      );

    // Page numbers
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.font('Helvetica').fontSize(7).fillColor('#98a2b3')
        .text(
          `${BRAND.name} — Page ${i + 1} of ${range.count}`,
          44, doc.page.height - 30, { width: W, align: 'center' }
        );
    }

    doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

function truncate(s, n) {
  s = String(s ?? '');
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}

function cleanDeclsValue(inspection, key) {
  return inspection.declarations?.[key]?.value || '';
}

function sectionTitle(doc, title, y) {
  doc.moveTo(44, y + 12).lineTo(44 + 240, y + 12).lineWidth(1).strokeColor(BRAND.accent).stroke();
  doc.fillColor(BRAND.accent).font('Helvetica-Bold').fontSize(10).text(title, 44, y);
}

function twoColTable(doc, rows, y) {
  rows.forEach(([k, v], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = 48 + col * ((doc.page.width - 88) / 2);
    const yy = y + row * 28;
    doc.fillColor('#66708a').font('Helvetica').fontSize(7.5).text(k.toUpperCase(), x, yy);
    doc.fillColor('#111827').font('Helvetica').fontSize(9)
      .text(truncate(v, 52), x, yy + 10, { width: (doc.page.width - 88) / 2 - 20 });
  });
}

function declTableHeader(doc, y) {
  doc.rect(44, y - 3, doc.page.width - 88, 14).fill('#eef2f7');
  doc.fillColor('#334155').font('Helvetica-Bold').fontSize(7.5)
    .text('FIELD', 48, y)
    .text('VALUE', 200, y)
    .text('CONFIDENCE', 415, y)
    .text('SOURCE', 480, y);
}

function checkTableHeader(doc, y) {
  doc.rect(44, y - 3, doc.page.width - 88, 14).fill('#eef2f7');
  doc.fillColor('#334155').font('Helvetica-Bold').fontSize(7.5)
    .text('RULE CODE', 48, y)
    .text('RULE TITLE', 148, y)
    .text('STATUS', 340, y)
    .text('CONF.', 420, y)
    .text('SOURCE REF.', 462, y);
}

module.exports = { generateInspectionPdf };
