const ROLES = {
  ADMIN: 'ADMIN',
  INSPECTOR: 'INSPECTOR',
  ANALYST: 'ANALYST',
};

const COMPLIANCE_STATUSES = ['COMPLIANT', 'NON_COMPLIANT', 'REQUIRES_REVIEW'];
const CHECK_STATUSES = ['PASS', 'FAIL', 'WARNING', 'NOT_APPLICABLE'];
const SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

const RULE_CATEGORIES = [
  'MANDATORY_DECLARATION',
  'NET_QUANTITY',
  'MRP',
  'MANUFACTURER_INFO',
  'PACKER_INFO',
  'IMPORTER_INFO',
  'COUNTRY_OF_ORIGIN',
  'CONSUMER_CARE',
  'DATE_DECLARATIONS',
  'UNIT_DECLARATIONS',
  'READABILITY',
  'FONT_SIZE',
  'PLACEMENT',
  'FORMATTING',
  'MISLEADING_DECLARATIONS',
  'OTHER',
];

const VALIDATION_TYPES = [
  'MANDATORY_FIELD',
  'MRP',
  'NET_QUANTITY',
  'DATE',
  'MANUFACTURER',
  'IMPORTER',
  'COUNTRY_OF_ORIGIN',
  'CONSUMER_CARE',
  'FONT_SIZE',
  'READABILITY',
  'PLACEMENT',
  'FORMATTING',
  'MISLEADING_CLAIMS',
];

// Canonical declaration field keys used across OCR extraction + rule engine + UI
const FIELDS = {
  PRODUCT_NAME: 'PRODUCT_NAME',
  BRAND_NAME: 'BRAND_NAME',
  COMMODITY_IDENTITY: 'COMMODITY_IDENTITY',
  NET_QUANTITY: 'NET_QUANTITY',
  MRP: 'MRP',
  INCLUSIVE_OF_ALL_TAXES: 'INCLUSIVE_OF_ALL_TAXES',
  MANUFACTURER_NAME: 'MANUFACTURER_NAME',
  MANUFACTURER_ADDRESS: 'MANUFACTURER_ADDRESS',
  PACKER_NAME: 'PACKER_NAME',
  PACKER_ADDRESS: 'PACKER_ADDRESS',
  IMPORTER_NAME: 'IMPORTER_NAME',
  IMPORTER_ADDRESS: 'IMPORTER_ADDRESS',
  COUNTRY_OF_ORIGIN: 'COUNTRY_OF_ORIGIN',
  MFG_DATE: 'MFG_DATE',
  PACK_DATE: 'PACK_DATE',
  IMPORT_DATE: 'IMPORT_DATE',
  BEST_BEFORE: 'BEST_BEFORE',
  CONSUMER_CARE_PHONE: 'CONSUMER_CARE_PHONE',
  CONSUMER_CARE_EMAIL: 'CONSUMER_CARE_EMAIL',
  CONSUMER_CARE_ADDRESS: 'CONSUMER_CARE_ADDRESS',
  CUSTOMER_CARE_DETAILS: 'CUSTOMER_CARE_DETAILS',
  BATCH_NUMBER: 'BATCH_NUMBER',
};

const IMAGE_LABELS = [
  'FRONT_PACKAGE',
  'BACK_PACKAGE',
  'SIDE_IMAGE',
  'LABEL_CLOSEUP',
  'LISTING_SCREENSHOT',
  'BARCODE_QR',
];

const NOTIFICATION_TYPES = ['INFO', 'SUCCESS', 'WARN', 'CRITICAL'];

module.exports = {
  ROLES,
  COMPLIANCE_STATUSES,
  CHECK_STATUSES,
  SEVERITIES,
  RULE_CATEGORIES,
  VALIDATION_TYPES,
  FIELDS,
  IMAGE_LABELS,
  NOTIFICATION_TYPES,
};
